### ISSUE TITLE
plan k8s deployment architecture for bsd, schema store & biovalidator

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#110]
have a meeting to discuss:
- [x] deployment diagram
- [x] one namespace per env with bsd, schema, biovalidator vs namespace per service

**Comment by theisuru** [comment]
Deployment diagram available [here](https://app.diagrams.net/#G1RMoXq4rdLotCEMD4b-25ayYu0fe5DgFE#%7B%22pageId%22%3A%22yPxyJZ8AM_hMuL3Unpa9%22%7D)
Deployment details at [confluence page](https://www.ebi.ac.uk/seqdb/confluence/display/BSD/What+Runs+Where+-+2023)
