### ISSUE TITLE
text search with additional filters ignores other filters

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#138]

**Comment by snathanvj** [comment]
@amnonkhen could you please provide a step to reproduce this, I think this has been fixed already and  working correctly now.

**Comment by snathanvj** [comment]
PR for this: no test cases added yet.  

https://github.com/EBIBioSamples/json-schema-store/pull/57

script to update synthetic field(created just for partial text search by combining few other fields )

`
db.schemas.updateMany(
    {}, 
    [
        {
            $set: {
                searchable: {
                    $trim: {
                        input: {
                            $reduce: {
                                input: [
                                    "$accession",
                                    "$description",
                                    "$title",
                                    "$name",
                                    "$group"
                                ],
                                initialValue: "",
                                in: {
                                    $concat: [
                                        "$$value",
                                        { $cond: [{ $eq: ["$$value", ""] }, "", " "] },
                                        { $ifNull: ["$$this", ""] }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    ]
)
`

**Comment by amnonkhen** [comment]
Link on how to add a db migration script that will update those values upon startup. There is a spring feature for it.

See [how it's done in HCA](https://github.com/ebi-ait/ingest-core/blob/dev/src/main/java/org/humancellatlas/ingest/migrations/MongoChangeLog.java)

More docs [here](https://chatgpt.com/share/673f460e-3dc4-8013-8a94-c85892da3067) or [here](https://github.com/mongobee/mongobee)

**Comment by snathanvj** [comment]
PR for front end works to use newly updated API instead of two APIs: https://github.com/ebi-ait/checklist-editor/pull/12
