### ISSUE TITLE
traffic manager rule for checklist editor dev (wwwint)

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#152]

**Comment by snathanvj** [comment]
PR has been merged https://gitlab.ebi.ac.uk/wp/wp-traffic-manager/-/merge_requests/1434

**Comment by snathanvj** [comment]
Checked in biosamples test and dev environment , I don't see application is accessible using cluster url. 

The URL Amnon shared in slack must be in different namespace.
 To discuss with @amnonkhen

**Comment by amnonkhen** [comment]
The problem is that the ingress rule did not have a `host` in it. I fixed it in the cluster and also in the helm chart and gitlab ci pipeline.

**Comment by snathanvj** [comment]
Still I could not access the application with cluster url.
