### ISSUE TITLE
Issue with editing fields in wwwint environment

### ISSUE THREAD

**Issue by theisuru** [ebi-ait/checklist#156]
There is no problem creating and editing text fields in wwwint environment. The `pattern` field seems to be giving an error without anything reporting in the console. Need to investigate further why it is giving a regex error `Value should be a valid regular expression.`. 

![Image](https://github.com/user-attachments/assets/5fff866a-e382-4b48-9a32-819b79601316)

**Comment by theisuru** [comment]
Seems to be a problem with actual regex being used. Once this is fixed, it can be saved without an issue. 
@amnonkhen could you please report here if you find more issues.

**Comment by amnonkhen** [comment]
The validation error should not be reported to console. It is the normal functioning of the checklist editor. If you are getting an error for the regex of your field, it means the regex you are using is invalid. Please post here the regex you used, so it can be investigated further. Checking the *collection field* in my local environment I do not see this validation problem.

**Comment by amnonkhen** [comment]
Also, please name tickets in a way that describes the issue, like "cannot save pattern fields due to validation error"

**Comment by theisuru** [comment]
This is the issue you reported. Only after investingation figured this is a problem with the regex.
