### ISSUE TITLE
"connection not private" error on wwwint

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#157]
our projects on wwwint show a "connection is not private" error:
- https://wwwint.ebi.ac.uk/ait/biovalidator
- https://wwwint.ebi.ac.uk/biosamples/checklist-editor
![Image](https://github.com/user-attachments/assets/90732a68-f639-4f36-bdf8-b7d606e61285)

I created [SNOW ticket INC0060994](https://embl.service-now.com/esc?id=ticket&is_new_order=true&table=incident&sys_id=3d3669ae1b6516503182bb35464bcb1c)

**Comment by Jeena-Rajan** [comment]
monitoring endpoint for this certificate was incorrect. Resolved by ITservices now
