### ISSUE TITLE
field units is missing from ui

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#164]
The field units are imported from the XML and are in the generated json-schema, but they are not shown in the UI.
It should be possible to set and edit field units in the UI.

**Comment by Wkt8** [comment]
Alex has mentioned that he cannot find them in the generated json-schema when polling the schema store API, can we double check that the units are in the generated json-schema?

**Comment by theisuru** [comment]
`units`  are not exported when exporting fields. This needs to be added to the model and exported. 
- Addd units property to the Field model
- Import units when importing checklists from ENA
- Export units field when exposing checklists as JSON Schema

**Comment by theisuru** [comment]
Add `units` as an array in `Field` edit page
