### ISSUE TITLE
Trying to edit a schema redirects to login page

### ISSUE THREAD

**Issue by snathanvj** [ebi-ait/checklist#166]
Login and try to edit older version of a checklist (just update any field and  click save button), it redirects again to login page. NOTE: json-schema-store API does not allow editing older version it return 403 status code with error message.

Editing a latest version correctly shows success message and redirects to intended checklist listing page.

May be this issue is limited to failure/reject cases.

**Comment by amnonkhen** [comment]
Editing non latest should not be available in the UI, so this problem will not be possible once the edit button is hidden.

**Comment by snathanvj** [comment]
PR to hide edit button for non editable field https://github.com/ebi-ait/checklist-editor/pull/9

**Comment by amnonkhen** [comment]
not relevant
