### ISSUE TITLE
fix json-schema exporting

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#169]
BioSamples is using `/registry/schemas/BSDC00001` but the checklist model is converted to json schema in `/exporter/schemas?id=ERC000013:1.1`.

**Comment by theisuru** [comment]
- Exporting should also work under previous URL
- Handle `alias` for ENA directrly imported checklists (v1.0)
- Checklist retrieve without version should return latest version

**Comment by theisuru** [comment]
- `/exporter/schemas/{id}` endpoint is no longer available
- All the exports are under `/registry/schemas/{idOrAccession}`
