### ISSUE TITLE
Run validation on json documents using biovalidator

### ISSUE THREAD

**Issue by Jeena-Rajan** [ebi-ait/checklist#21]

**Comment by theisuru** [comment]
[accessions here](https://github.com/ebi-ait/checklist-converter/blob/main/data/accessions.csv)

Current validation is in a test case right now [here](https://github.com/ebi-ait/checklist-converter/blob/main/src/test/java/uk/ac/ebi/checklistconverter/ena/ChecklistConverterServiceTest.java)

**Comment by amnonkhen** [comment]
I run a biovalidator image locally using docker compose and am getting HTTP 500 error with the following text:
```json
{"errors":"Error: certificate has expired"}
```
In the biovalidator logs I notice the following error
```
biovalidator-1  | 2024-05-24T20:46:45.687Z [debug] Received POST request.
biovalidator-1  | async schema compiled encountered and error
biovalidator-1  | RequestError: Error: certificate has expired

```

**Comment by amnonkhen** [comment]
Ended up working using a different biovalidator image than the one in the docker compose
```bash
docker pull quay.io/ebi-ait/biovalidator:2.2.1
docker run -p 3020:3020 -d quay.io/ebi-ait/biovalidator:2.2.1
```

**Comment by amnonkhen** [comment]
There are a few 413 errors: 
```json
{"error":"request entity too large"}
```
