### ISSUE TITLE
comparison of validation results - runs 001, 002

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#23]
Output format:

a file where each line is:

1. document accession
2. checklist accession
3. ena validation status: success, failure, script error 
4. biovalidator validation results: success, failure, script error

**Comment by snathanvj** [comment]
@theisuru @amnonkhen where can I find the validation results to compare

**Comment by snathanvj** [comment]
@theisuru @ESapenaVentura Comparison itself is not a big work but getting the required output format is something we have to do first. I can decide what has to be done in comparison  only when I have the output format for the two validation result. I will move my ticket to blocked state for now.

**Comment by amnonkhen** [comment]
results of comparing run 002: https://docs.google.com/spreadsheets/d/1auCJ3zmU3Xd6nEJVanRLLXXwqs5KPl1-ntXa3HMuxgg/edit#gid=0

**Comment by ESapenaVentura** [comment]
So far, I have checked manually ~20 different documents and all of the discrepancies between validations are because of synonyms.

I feel there's too much noise for a quick, reliable comparison - I would wait until we fix the issue with the synonyms and then compare
