### ISSUE TITLE
add json validation to ena flow

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#34]
Discussing with member of the ENA team (Rasko) about where in the ENA flow the XML documents are validated against the checklist. Keep that piece of code and add to it the part that will not interfere with the ENA work to send it to validation with JSON. 

For now, XML validation is not being replaced, adding JSON validation at the same timepoint. Run both in parallel and have some comparisons to see if they give similar results. 

## Acceptance Criteria
- [x] find relevant ena code locations
- [x] sequence diagram depicting the ena xml validation flow
- [x] understand how to test these code changes
- [x] deployment procedure to ena dev
- [ ] json validation is to be enabled or disabled using an environment variable.
- [ ] json validation should not interfere at all with the ena flow. It should not change it what so ever, even if there is an exception in the json schema. There should be a unit test to verify it.
- [ ] test on dev
- [ ] make sure there is no performance degradation

**Comment by snathanvj** [comment]
https://mermaid.live/edit#pako:eNqdU91qwjAUfpVDrjboXiAXwja9EHQXdrAxBInpUePSnC5Jy0R896WmtTpFx3qV5Hw_yTn9tkxShowzh18lGol9JZZW5FMD4ZNaofEPvd7b4Gn4MpsM0lfuynmuPDiRFxph7chEbAcJ-HQPmj2T8Za0RsuDjt1E5FmxNsC5MvuCc4pMirZSEjk0brWNa3wuIq9ISDIV2qgByniC9_EIaL5G6W9IppPH2YhEFu4PldAqEx5BmAykxXrpDpzmZQc8BDYc09UCDEEhrENAa8m6pJOMzbxrZ-CJtAO5Qvnp7m8qL9FHrFbOw7AP4YWnZwuy4MI2F63lv24MtUwceycTS0nXnaVQ5sj7O9eN918MhdZROwlO1a0GX54bcLAoURVXpwuX_tLf1HPASRbOnLoIBFwMD28QLGE52lyoLIRtW-OnzIe24JTxsAyZK1Z-U4Tt1OwCWJSe0o2RjHtbYsLKom5vk07GF0K7cIqZ8mTHMcL7JLfIwb7SsgthPoha3u4Hi2tiBg

**Comment by snathanvj** [comment]
Webin_REST : https://github.com/enasequence/sub-sra
Files changes required: 
WebinSubmissionService.java (submit method lines between 83 to 97 converts xml to json ), 
SRALoader.java (validate method, probably  line 300 to 310 have to be duplicated ), 
 SRASampleParser.java (line 151 validateAndFind(...))

**Comment by snathanvj** [comment]
@amnonkhen I need more clarity on this task
1) Where should we need to put the validation result for our json schema flow?
2)  Are we making the changes in Webin-REST , 
    a) so that in future we just can use the same code for json based validation and cut-off the xml validation part easily(this is what I thought)
    b)we just need to validate the sample against json based checklist schema, in this case we just can run it as an independent pipeline(probably using pipelite which will save the logs in pipelite_log table)

if 1.a is the answer then shall I go ahead and make changes and create a PR.

**Comment by amnonkhen** [comment]
- json validation is to be enabled or disabled using an environment variable.
- json validation should not interfere at all with the ena flow. It should not change it what so ever.
- I don't think an I don't think an independent pipeline would do the trick because the submitter expects the validation result to be sent to the in the http response.

**Comment by theisuru** [comment]
After the call with Dipayan and Senthil, it is quite clear how we want to handle this. 
We have identified where the JSON validation code could fit in with ENA flow. We can inject this where XML validation is happening right now before we submit to BioSamples. (Senthil probably can add more details about this)

ENA is using GCP Cloud Logging and monitoring. Once both JSON and XML validation is finished we will send related metrics via micrometer and further send logs to Cloud Logging if there is any discrepancy between the two results.

**Comment by amnonkhen** [comment]
Thanks. Will review shortly.
Please rename branch ck-_nn_ so the GitHub autolinks work

**Comment by amnonkhen** [comment]
Following meeting with ENA team (Dipayan) we realised ENA will remove validation, and everything will be delegated to BioSamples, so we don't need to do anything in ENA.
