### ISSUE TITLE
validation comparison - run 007

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#35]
Run on the BioSamples schema.

Running instructions: see #25

For the 400 accession set:
- [x] script to retrieve samples from BioSamples by accession
- [x] change json schema conversion templates 
- [x] validate using biovalidator
- [ ] compare results

**Comment by amnonkhen** [comment]
@theisuru I see in the run007 directory several documents that failed validation:
- SAMEA111303371.json
- SAMEA111303379.json
- SAMEA111308902.json
- SAMEA111309343.json
- SAMEA111309356.json
- SAMEA111309385.json
- SAMEA111301963.json

Have you investigated what the issue is?

**Comment by theisuru** [comment]
Related to `allOf` entry in checklist 56, empty mandatory field. Fixed and re-running in the same run.
