### ISSUE TITLE
error messages from json schema validation are vague

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#37]
Usable error messages means that the problematic document attribute is clear and the the problem is also clear.
If not, the conversion process needs to be improved.

In the ENA json schema we used arrays, which made the errors difficult to understand. This issue might be less critical when using theBioSamples format which does not have arrays.

tasks:
- [x] run a few invalid BioSamples documents through biovalidator 
- [x] analysis the legibility and clarity of the error. Do you know what the problem is?
- [x] come up with possible avenues for fixing a problem, should there be one

**Comment by amnonkhen** [comment]
[![](https://mermaid.ink/img/pako:eNp9U0Fu2zAQ_ArBQ09KkMQ2YfMQIG1ToEDTQ3MpCl0ociVvK5GqSDp2Df-9K1FxBDuJTuLOzM6OuNpz7QxwyT38jWA1fEZVdarJLaOnVV1Aja2ygX2qEWw4r99_vzsvfkT3qJq2Bp_bhCb5xe0t8SXzsWgwsJ8P35hxOjEIeIZL3Pb12BwdJ6B2dgNdYMGx395ZhnZix0rXNWoUWReAOSKzQVjskq_3SLIAk5QMtugD2oqVtXuSfe8CWAcNqU1iHYd4MaMcYE1vyZTWMPSlHif8wXujajSKxtk29Wt4EbE2ZKgB23F6av1WjC93X39giVqF8yQWnsYQoyeefaPjAO8lmqg_vB5v0vLiJGev6sDHOvieeBLo_dwT1KsN9LOb4gUiLO2SpKn-WFeDqaBfFJ7xBujy0dA673tBzsOaoJxLeqWtbtdh19Ixtwcix7a_kHuDwXVchi5CxlUM7nFn9fM5ccZ_gstS1Z6qtOJc7vmWy5uluLyar8RSCHElVstZxndcLi5Xs8Vifi1uVjMxnwlxyPg_56jBdcZhMHxIfx3tcokVH1r-GhjJt3OxWqfD4T_RCiqE?type=png)](https://mermaid.live/edit#pako:eNp9U0Fu2zAQ_ArBQ09KkMQ2YfMQIG1ToEDTQ3MpCl0ociVvK5GqSDp2Df-9K1FxBDuJTuLOzM6OuNpz7QxwyT38jWA1fEZVdarJLaOnVV1Aja2ygX2qEWw4r99_vzsvfkT3qJq2Bp_bhCb5xe0t8SXzsWgwsJ8P35hxOjEIeIZL3Pb12BwdJ6B2dgNdYMGx395ZhnZix0rXNWoUWReAOSKzQVjskq_3SLIAk5QMtugD2oqVtXuSfe8CWAcNqU1iHYd4MaMcYE1vyZTWMPSlHif8wXujajSKxtk29Wt4EbE2ZKgB23F6av1WjC93X39giVqF8yQWnsYQoyeefaPjAO8lmqg_vB5v0vLiJGev6sDHOvieeBLo_dwT1KsN9LOb4gUiLO2SpKn-WFeDqaBfFJ7xBujy0dA673tBzsOaoJxLeqWtbtdh19Ixtwcix7a_kHuDwXVchi5CxlUM7nFn9fM5ccZ_gstS1Z6qtOJc7vmWy5uluLyar8RSCHElVstZxndcLi5Xs8Vifi1uVjMxnwlxyPg_56jBdcZhMHxIfx3tcokVH1r-GhjJt3OxWqfD4T_RCiqE)

**Comment by Wkt8** [comment]
The Invalid JSON message could be improved by adding line numbers

**Comment by amnonkhen** [comment]
Need to reevaluate error messages after fixing the conversion to include field aliases.

**Comment by theisuru** [comment]
New JSON Schema is [here](https://github.com/ebi-ait/checklist-converter/tree/main/schema). Use *-BSD.json files for BioSamples Schema.

**Comment by theisuru** [comment]
We can add new invalid samples in [this directory](https://github.com/ebi-ait/checklist-converter/tree/main/src/test/resources/samples). We will add them to unit/integration tests later.

**Comment by Wkt8** [comment]
- [ ] create a set of invalid documents and test against biosamples new schema 
- [ ] store those documents on the checklist-converter github
- [ ] store the error messages on the checklist-converter github
- [ ] errors are for the following
- [ ] mandatory field
- [ ] data type
- [ ] enum
- [ ] pattern
- [ ] json

**Comment by Wkt8** [comment]
Added new invalid samples in [this directory ](https://github.com/ebi-ait/checklist-converter/tree/ck-37-wei-add-specified-errors-to-sample/src/test/resources/samples/ERC000011) that Isuru shared. Three files are there, corresponding to errors for 'mandatory field', 'enum' and 'pattern'. 

Data-type is unable to be tested as all of data types were string type.
JSON error is as above, broad and lacking information when tested in biovalidator. 

`Unable to parse the JSON in the input fields.`

**Comment by Wkt8** [comment]
Completed: see here @amnonkhen if this is what you are looking for, it is very similar to the before task. 
https://github.com/ebi-ait/checklist-converter/blob/ck-37-wei-add-specified-errors-to-sample/src/test/resources/samples/ERC000011/error_messages.md
