### ISSUE TITLE
run 008 - compare invalid document

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#39]
Running instructions: see #25

Definition of done:
- [x] all output related to this task should be saved in the shared directory of this run (`/nfs/production/tburdett/workstreams/fairification/checklists/data/run008`)
- [x] generate the invalid documents, grouped in directory according to type, e.g. "missing mandatory", "bad pattern", etc.
- [x] the results of sending those documents for validation in biovalidator
- [x] The analysis of the results: did we get the expected errors from biovalidator
- [x] analyse the problems with invalid patterns being accepted by the json schema
   - see ticket #53

**Comment by snathanvj** [comment]
I have executed the script for mandatory and enum errors , details are in #38

**Comment by snathanvj** [comment]
erroneous files are in same directory with error_type in file name otherwise all done.

**Comment by snathanvj** [comment]
generated files are here

/nfs/production/tburdett/workstreams/fairification/checklists/data/run008/invalid

biovalidator outputs are here:

/nfs/production/tburdett/workstreams/fairification/checklists/data/run008/invalid/validation_result
Comparison results are here:

/nfs/production/tburdett/workstreams/fairification/checklists/data/run008/enum_error_comparison.txt
/nfs/production/tburdett/workstreams/fairification/checklists/data/run008/mandatory_error_comparison.txt

**Comment by ESapenaVentura** [comment]
- **unmodified files**: `/nfs/production/tburdett/workstreams/fairification/checklists/data/run008/jsons/original/`
- **Errored pattern files**: `/nfs/production/tburdett/workstreams/fairification/checklists/data/run008/jsons/invalid_pattern`
- **Extra file that indicates what was changed**: `/nfs/production/tburdett/workstreams/fairification/checklists/data/run008/pattern_invalidation_error_report.csv`

Will do the biovalidator output/comparison now

**Comment by ESapenaVentura** [comment]
**Pattern validation**

I have prepared [a spreadsheet](https://docs.google.com/spreadsheets/d/1fJfrryVWMTndqj0GnuF3sChQz3ZnUy3Xv9VRxNNWj6Q/edit?gid=0#gid=0) that contains some details about the validations that did not function correctly (aka, should have invalid value but it does not). I suspect this may be a problem of the regex and validation, rather than the schemas or the script not working correctly - Currently investigating

**Comment by ESapenaVentura** [comment]
There are 7 unique patterns:

- [+-]?[0-9]+.?[0-9]*
- (0|((0\.)|([1-9][0-9]*\.?))[0-9]*)([Ee][+-]?[0-9]+)?
- [+-]?(0|((0\.)|([1-9][0-9]*\.?))[0-9]*)([Ee][+-]?[0-9]+)?
- ([+-]?(0|((0\.)|([1-9][0-9]*\.?))[0-9]*)([Ee][+-]?[0-9]+)?)|((^not collected$)|(^not provided$)|(^restricted access$)|(^missing: control sample$)|(^missing: sample group$)|(^missing: synthetic construct$)|(^missing: lab stock$)|(^missing: third party data$)|(^missing: data agreement established pre-2023$)|(^missing: endangered species$)|(^missing: human-identifiable$))
- [+-]?[0-9]+
- ^150|1[0-4][0-9]|[1-9][0-9]|[0-9]|not provided$
- ((0|((0\.)|([1-9][0-9]*\.?))[0-9]*)([Ee][+-]?[0-9]+)?)|((^not collected$)|(^not provided$)|(^restricted access$)|(^missing: control sample$)|(^missing: sample group$)|(^missing: synthetic construct$)|(^missing: lab stock$)|(^missing: third party data$)|(^missing: data agreement established pre-2023$)|(^missing: endangered species$)|(^missing: human-identifiable$))

**Comment by ESapenaVentura** [comment]
All the patterns validate against the `123` part of the invalid value `__XYZ_BANANA_123%$£`. Possible options are:

- Accept that and try another invalid value
- Talk with ENA to understand if validation is supposed to be unanchored - if the regexp validation is expected or not
