### ISSUE TITLE
enable validation in BioSamples

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#45]
ENA needs to send BioSamples a request to accession the sample as well as validate it.
If it is implemented, communicate to ENA team how to do it, if not, implement it and communicate to ENA.

DOD:

- [x] Is ENA calling the same apis when it submits a single documents or a bulk submission?
   - ENA is just using bulk submission 
- [x] change BioSamples to send the document to biovalidator, cancel accessioning if invalid
   - [x] pending PR review: EBIBioSamples/biosamples-v4#714
- [x] return validation result to caller, e.g. ENA. Agree on format with Submissions team.
   - [x] validation results returned
   - [x] talk to Dipayan about payload structure
- [x] deploy on dev and test api calls and integration with ENA 
- [x] add some detail to the diagram below, to specify endpoints, main classes etc. (no need to delve into details)

Further breakdown tasks
- [x] Add submission errors to bulk submission response (as a list of errors)
- [x] Change biosamples client to reflect new response for bulk submissions

**Comment by amnonkhen** [comment]
[![](https://mermaid.ink/img/pako:eNqNVNtu2zAM_RVCD3vKAufeGEOAdt2AAdse1pdi8zAoMp1otSVPl6RZkH8fZeeiwikwGzBkkoeHOqS0Z0LnyFJm8Y9HJfBe8pXhVaaAnpobJ4WsuXLwvpSoXNf-4ett13gn9QOv6hJt12fFGiv-yzptsOuttFrp-7tMhTc4W963iwURpWD9spIOHr98hlyLNoIcJ3chn4PdV-dSI6fQaoPGgdPw22oFUkV1QqFNxY8gpR2CpmBogMsdfLz99E0WUnAnCekwUggUbqEo9TaFDS9l3oa8TN4GX0lNHxC8LC0spbbHaLdGeLc0CyADwpbvgFsQ3hjaVbm7lutClcIPx-3Tz5jdosqbfCRN2H1UZlRZq1ScKeCCLjHgDXAh0FpaS7W6oCM6yvKiySms8NT2oKXML7A4rgEe-0-tRCfWUBhdQRiHV3hItWNx2pz1x2aj3lKBR4L_1GzpZZmD9q727lXKGBcDYCvduulbJJdB60sXD0CcLaRrxuAKAk69oSZ0RrnlNShQ1t1Bt3yDYQDz5cVFvvYkpdTAJ6VLzFcYjgnrsQpp9GVOt8A-ADJGA1hhxlJa5lhwqidjmTpQKPdOP-yUYKkzHnvMaL9as7TgpaU_Xwf1j1fI2Urn-rvW1QlCvyzds2eWzub9yXA2mk6T6WxwM5pOemzH0smon4xvktkomU3Hg-FwcOixvw1-0E-S-fxmnsyGk3EyGCbTwz9LB4mI?type=png)](https://mermaid.live/edit#pako:eNqNVNtu2zAM_RVCD3vKAufeGEOAdt2AAdse1pdi8zAoMp1otSVPl6RZkH8fZeeiwikwGzBkkoeHOqS0Z0LnyFJm8Y9HJfBe8pXhVaaAnpobJ4WsuXLwvpSoXNf-4ett13gn9QOv6hJt12fFGiv-yzptsOuttFrp-7tMhTc4W963iwURpWD9spIOHr98hlyLNoIcJ3chn4PdV-dSI6fQaoPGgdPw22oFUkV1QqFNxY8gpR2CpmBogMsdfLz99E0WUnAnCekwUggUbqEo9TaFDS9l3oa8TN4GX0lNHxC8LC0spbbHaLdGeLc0CyADwpbvgFsQ3hjaVbm7lutClcIPx-3Tz5jdosqbfCRN2H1UZlRZq1ScKeCCLjHgDXAh0FpaS7W6oCM6yvKiySms8NT2oKXML7A4rgEe-0-tRCfWUBhdQRiHV3hItWNx2pz1x2aj3lKBR4L_1GzpZZmD9q727lXKGBcDYCvduulbJJdB60sXD0CcLaRrxuAKAk69oSZ0RrnlNShQ1t1Bt3yDYQDz5cVFvvYkpdTAJ6VLzFcYjgnrsQpp9GVOt8A-ADJGA1hhxlJa5lhwqidjmTpQKPdOP-yUYKkzHnvMaL9as7TgpaU_Xwf1j1fI2Urn-rvW1QlCvyzds2eWzub9yXA2mk6T6WxwM5pOemzH0smon4xvktkomU3Hg-FwcOixvw1-0E-S-fxmnsyGk3EyGCbTwz9LB4mI)

**Comment by theisuru** [comment]
Some changes are in a draft pull request. Need to speak with @dipayan1985 about APIs ENA is using. I assume they are only using Bulk submission endpoint. 
If ENA also using POST, PUT v2 endpoints, these changes should also be done there. 
EBIBioSamples/biosamples-v4#714

**Comment by theisuru** [comment]
- ENA is only using bulk submission endpoint
- Currently we bypass validation if the user==superuser. With changes, we will introduce validation for all users including superuser. 
- Change validation logic
 - Currently each samples is validated and persisted. If there is a validation error, samples upto the error is persisted.
 - New logic will do all validation first and then persist. If there is a validation error, no sample is persisted.

**Comment by theisuru** [comment]
Need to address comments from Dipayan in PR
EBIBioSamples/biosamples-v4#714

**Comment by theisuru** [comment]
Update: Deploying in BioSamples
There is a problem with BSD deployment pipeline with Gitlab. A problem with used image and ssh keys. (probably after upgrade to Gitlab). Will check this issue with Dipayan on Friday. Untill then doing a manual deployment to the dev environment.

**Comment by theisuru** [comment]
Calling the API returns error message. This should instead return samples that were accessioned. Exception is not catched correctly. Need to fix and test this in the local environment before deploying again. 

```
Checklist validation failed: Sample validation failed: [{"dataPath":"/characteristics/geographic location (latitude)/0/text","errors":["should match pattern \"(^[+-]?[0-9]+.?[0-9]{0,8}$)|(^not collected$)|(^not provided$)|(^restricted access$)|(^missing: control sample$)|(^missing: sample group$)|(^missing: synthetic construct$)|(^missing: lab stock$)|(^missing: third party data$)|(^missing: data agreement established pre-2023$)|(^missing: endangered species$)|(^missing: human-identifiable$)\""]},{"dataPath":"/characteristics/geographic location (longitude)/0/text","errors":["should match pattern \"(^[+-]?[0-9]+.?[0-9]{0,8}$)|(^not collected$)|(^not provided$)|(^restricted access$)|(^missing: control sample$)|(^missing: sample group$)|(^missing: synthetic construct$)|(^missing: lab stock$)|(^missing: third party data$)|(^missing: data agreement established pre-2023$)|(^missing: endangered species$)|(^missing: human-identifiable$)\""]}]
```

**Comment by theisuru** [comment]
I was testing using AAP users, hence the error message for the API. Using a webin user will return only the valid samples. 
This is not currently returning error messages for invalid samples. Need to talk with @dipayan1985 how we can return error messages. 

Next, I will continue with the load test.

**Comment by theisuru** [comment]
Following changes are pending
- Add submission errors to bulk submission response
- Change biosamples client to reflect new response for bulk submissions

**Comment by theisuru** [comment]
Now response contains successful samples and error messages. Since the response format has changed, now we need to modify biosamples-client to reflect these changes.

**Comment by theisuru** [comment]
Dipayan has pulled and integrated new changes in biosamples client. There is a one problem that needs to be discussed tomorrow. 

ERC000026 is a EGA checklist. This is not available in ENA checklist API, hence not available in schema-store. 
How do we handle this? see #68

**Comment by dipayan1985** [comment]
@theisuru

Hi Isuru and Amnon, I am doing the Webin changes for readiness but as we had to rollback BSD in test, I am connecting Webin to BSD local for, there are no checklists in local so it is always 404 for validation requests. Can we work out something to load the checklists using a script and dump to the schemastore database after docker-integration?

**Comment by amnonkhen** [comment]
> Can we work out something to load the checklists using a script and dump to the schemastore database after docker-integration?

@dipayan1985 what you suggest is possible, but there is a faster workaround you could use immediately which to point BioSamples to the dev json-schema-store in the `application.properties`.

**Comment by dipayan1985** [comment]
@amnonkhen, @theisuru
Set the JSON schema store to dev while running locally and validation messages for one submission done in Local Webin-REST to local BioSamples (lookup from dev JSON schema store) looks much better now:


******************** RECEIPT **********************
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="receipt.xsl"?>
<RECEIPT receiptDate="2024-07-29T11:25:16.470+01:00" submissionFile="test.xml" success="false">
     <SAMPLE alias="2024_07_29_11_25_14_516__EBI_SUB_SRA_TEST_ALIAS__3" status="PRIVATE"/>
     <SUBMISSION alias="2024_07_29_11_25_14_516__EBI_SUB_SRA_TEST_ALIAS__3_2024_07_29_11_25_14_516__EBI_SUB_SRA_TEST_ALIAS__3"/>
     <MESSAGES>
          <ERROR>2024_07_29_11_25_14_516__EBI_SUB_SRA_TEST_ALIAS__3 failed validation due to should have required property 'collection date'</ERROR>
          <ERROR>2024_07_29_11_25_14_516__EBI_SUB_SRA_TEST_ALIAS__3 failed validation due to should have required property 'geographic location (country and/or sea)'</ERROR>
          <ERROR>Failed to submit samples to BioSamples</ERROR>
          <ERROR>Failed to submit samples to BioSamples</ERROR>
          <ERROR>An exception occurred: java.lang.RuntimeException: Failed to submit all samples to BioSamples</ERROR>
     </MESSAGES>
     <ACTIONS>ADD</ACTIONS>
</RECEIPT>
```
Please ignore the last message of RuntimeException.
