### ISSUE TITLE
stress tests for biosamples validation

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#48]
- What are the current ENA benchmarks?
   - <100ms response time for submission
   - What is the expected throughout?
   - [x] Is there a load testing framework (e.g. JMeter)? - no
   - [x] Waiting for info from Dipayan
- according to results of load tests, if we don't meet the requirements, we could check: high availability for biovalidator in k8s: LB, error recovery, etc. This will be tracked in a new ticket.
- 

definition of done:
- [x] simulate different numbers of concerrent users
- [x] simulate different batch sizes
- [ ] test on a few checklists (include the most complex)

**Comment by dipayan1985** [comment]
<details>
<summary>Logs from K8 cluster:</summary>
```
Webin-REST 12:46:53 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 12:46:58 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 72 samples to BioSamples and the total time taken is 5015 milliseconds
Webin-REST 12:49:09 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 12:49:10 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 12 samples to BioSamples and the total time taken is 1209 milliseconds
Webin-REST 13:25:35 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 13:25:35 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 13:25:36 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 1 samples to BioSamples and the total time taken is 304 milliseconds
Webin-REST 13:25:36 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 1 samples to BioSamples and the total time taken is 342 milliseconds
Webin-REST 13:25:36 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 13:25:36 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 1 samples to BioSamples and the total time taken is 81 milliseconds
Webin-REST 13:25:36 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 13:25:36 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 1 samples to BioSamples and the total time taken is 64 milliseconds
Webin-REST 13:25:37 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 13:25:37 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 13:25:37 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 1 samples to BioSamples and the total time taken is 71 milliseconds
Webin-REST 13:25:37 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 1 samples to BioSamples and the total time taken is 77 milliseconds
Webin-REST 13:51:36 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 13:51:37 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 12 samples to BioSamples and the total time taken is 1252 milliseconds
Webin-REST 14:15:16 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 14:15:17 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 9 samples to BioSamples and the total time taken is 1035 milliseconds
Webin-REST 14:17:10 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 14:17:12 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 39 samples to BioSamples and the total time taken is 2424 milliseconds
Webin-REST 14:19:40 u.a.e.e.s.b.p.BioSampleSubmitter - Persisting all samples to BioSamples in 1 batch(s)
Webin-REST 14:19:47 u.a.e.e.s.b.p.BioSampleSubmitter - Stored 85 samples to BioSamples and the total time taken is 6291 milliseconds
```
</details>
On average per sample submission to BioSamples takes ~60-70 millis.

- Expected throughput - we should attempt to keep per sample submission time to <100 milliseconds
- We don't have any load testing framework, statistics are logged using micrometer stack driver to GCP monitoring

**Comment by theisuru** [comment]
Testing using a python script. If this is not enough we can consider using JMeter or similar app.
(Note: biovalidator caches schema and if it has a cache miss, request time could be significantly larger all of the tests below are carried after warmup)

## Test 1
ERC000022
Results for a single test. To get a good idea, we need to carry this for a large no of submissions and average. 
| no of samples | total time (ms) | time per sample (ms) |
|---------------|-----------------|----------------------|
| 1             | 245.16          | 245.16               |
| 100           | 2076.30         | 20.76                |
| 500           | 8886.27         | 17.77                |

Next:
Do parallel submissions

**Comment by Wkt8** [comment]
Variables: 
- Number of samples (10, 50)
- Type of submission (parallel submissions)
- Type of checklist (small (default), large (GSC))
- Status of sample (Valid, invalid) 

Clarify with Dipayan whether the single submission endpoint is being used, or only the bulk submission endpoint is in use.

**Comment by theisuru** [comment]
| no of samples | total time (ms) | time per sample (ms) |
|---------------|-----------------|----------------------|
| 1             | 245.16          | 245.16               |
| 2             | 209.90          | 104.95               |
| 3             | 227.97          | 75.99                |
| 4             | 227.07          | 56.77                |
| 5             | 234.24          | 46.85                |
| 10            | 343.98          | 34.40                |
| 50            | 842.43          | 16.85                |
| 100           | 2076.30         | 20.76                |
| 500           | 8886.27         | 17.77                |

Serial submissions (non-parallel)
| no of samples | run 1  | run 2  | run 3  | run 4  | run 5  | Average time for <br/>100 iterations |
|---------------|--------|--------|--------|--------|--------|--------------------------------------|
| 1             | 245.16 | 199.76 | 204.25 | 187.30 | 213.83 | 193.01                               |
| 10            | 32.49  | 31.64  | 32.25  | 34.54  | 32.51  | 37.31                                |
| 50            | 18.46  | 20.90  | 22.11  | 19.50  | 15.89  | 21.26                                |
| 100           | 15.80  | 16.05  | 16.12  | 29.08  | 18.67  | 20.36                                |
| 500           | 16.36  | 17.86  | 16.54  | 15.69  | 19.53  | 18.27                                |

**Comment by theisuru** [comment]
Again valid cases for ERC000022
Tests were carried out from EBI network, so results are not directly comparable to the above tables.

| no of samples | 5 threads | 10 threads | 30 threads | 100 threads      |
|---------------|-----------|------------|------------|------------------|
| 1             | 115.41    | 170.79     | 663.44     | 2077.15          |
| 5             | 46.36     | 45.02      | 135.32     | 482.59           |
| 10            | 22.92     | 28.57      | 86.44      | 317.84           |
| 50            | 17.08     | 23.22      | 44.96      | 162.29           |
| 100           | 15.74     | 22.48      | 50.74      | 114.19           |
| 500           | 17.20     | 21.33      | 48.84      | 500 server error |

**Comment by Jeena-Rajan** [comment]
Add column with 30 threads as big jump between 10 and 100 threads

**Comment by theisuru** [comment]
Serial run
<img width="1064" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejhBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b97e05340d829a9baab290ca6e5920660074539/image.png" alt="image.png" />

**Comment by theisuru** [comment]
with multiple submissions, results seems to be fairly consistent. This was run over the VPN. 

+-------------------+-----------+-----------+------------+------------+-------------+
| number of samples | count = 1 | count = 5 | count = 10 | count = 30 | count = 100 |
+-------------------+-----------+-----------+------------+------------+-------------+
|         1         |   136.99  |   130.67  |   135.33   |   138.84   |    139.44   |
|         2         |    85.84  |    86.23  |    85.51   |    93.81   |     91.57   |
|         3         |    68.19  |    68.84  |    68.70   |    73.57   |     73.01   |
|         4         |    67.61  |    63.65  |    61.25   |    65.43   |     63.90   |
|         5         |    57.34  |    58.45  |    58.08   |    63.48   |     59.77   |
|         10        |    55.27  |    52.13  |    51.39   |    52.32   |     52.85   |
|         50        |    40.06  |    41.11  |    42.14   |    43.54   |     44.25   |
|        100        |    43.48  |    43.68  |    44.55   |    42.68   |     41.44   |
+-------------------+-----------+-----------+------------+------------+-------------+

<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77c10a91e8232058b0e178339d706f69643541fe/myplot.png" alt="myplot.png" />
