### ISSUE TITLE
document schema-store db structure

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#50]
The schema store currently uses a mongo db.
Its structure needs to be documented.

DOD:
- [ ] diagram in the readme file of the repo: spring boot api, mongo db, etc.
- [ ] db structure that explains the model for storing versioned schema documents

**Comment by theisuru** [comment]
Merging changes in checklist-converter
Upgrading to spring-boot 3.x
Too much changes in spring-security. Disabling security temporarily
