### ISSUE TITLE
pattern schema attributes accepting bad values

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#53]
Run 008 (#39) found that some pattern attributes accept invalid values.

- [x] Is this happening also on ENA?
  - [RegexFieldValidator](https://github.com/enasequence/sub-sra/blob/a819f9045dc9401a6052259bc51547d2481a1ebf/sra-core/src/main/java/uk/ac/ebi/ena/sra/validation/checklist2/RegexFieldValidator.java#L38) is the class responsible for running regex validation in ENA. It appears to be using `find()` which is running a partial match. This is verified with added unit tests to the ena code. See PR  enasequence/sub-sra#241
- [x] is ena cleaning bad values in attributes like _depth_ , e.g. "ABC123" to extract just the number? Do a test submission in ena dev.
   - Dipayan confirmed today that ENA is not doing such cleanup. 
- [x] Is biovalidator's json schema validation using ajv does a partial match?
  - AJV does a partial match, so regexp need to be anchored 
- [x] Which checklists are affected?
  - see [spreadsheet](https://docs.google.com/spreadsheets/d/1fJfrryVWMTndqj0GnuF3sChQz3ZnUy3Xv9VRxNNWj6Q/edit?gid=0#gid=0) in the run 008 ticket
- [ ] How do we fix this? 
    - [ ] TODO @isuru: by changing the regular expressions to anchor the values during conversion
       - idea: change the [velocity template](https://github.com/ebi-ait/checklist-converter/blob/a7ad7bd9fc1319f439698baa4d86c91d961cfef3/src/main/resources/templates/biosamples_template.vm) to wrap each pattern with `^(` and `)$` 
       - another option is to do it in java
    - [x] by opening a ticket to ena helpdesk to fix all regexps - Jeena emailed today.
    - [ ] by otherwise changing biovalidator? - no

**Comment by ESapenaVentura** [comment]
All unique patterns in the checklists:

<details> <summary> Unique patterns </summary>

- (0|((0\.)|([1-9][0-9]*)))
- [+-]?(0|((0\.)|([1-9][0-9]*\.?))[0-9]*)([Ee][+-]?[0-9]+)?
- ^[0-9]{4}(-[0-9]{2}(-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?$
- [0-9]+(\.[0-9]*)?
- (0|((0\.)|([1-9][0-9]*\.?))[0-9]*)
- (^[ESD]RS\d{6,}$)|(^SAM[END][AG]?\d+$)|(^EGAN\d{11}$)
- ^[0-9]{4}(-[0-9]{2}(-[0-9]{2})?)?$
- (^[ESD]R[SR]\d{6,}(,[ESD]R[SR]\d{6,})*$)|(^SAM[END][AG]?\d+(,SAM[END][AG]?\d+)*$)|(^EGA[NR]\d{11}(,EGA[NR]\d{11})*$)|(^[ESD]R[SR]\d{6,}-[ESD]R[SR]\d{6,}$)|(^SAM[END][AG]?\d+-SAM[END][AG]?\d+$)|(^EGA[NR]\d{11}-EGA[NR]\d{11}$)
- [+-]?[0-9]+
- [\d][0-4]?(\.[\d]{1,10})?
- (^[+-]?[0-9]+.?[0-9]{0,8}$)
- ([0-9]*)
- ^[12][0-9]{3}(-(0[1-9]|1[0-2])(-(0[1-9]|[12][0-9]|3[01])(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?(/[0-9]{4}(-[0-9]{2}(-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?)?$
- (^(E|D|S)RZ[0-9]{6,}$)|(^GC(A|F)_[0-9]{9}.[0-9]+$|^[A-Z]{1}[0-9]{5}.[0-9]+$|^[A-Z]{2}[0-9]{6}.[0-9]+$|^[A-Z]{2}[0-9]{8}$|^[A-Z]{4}[0-9]{2}S?[0-9]{6,8}$|^[A-Z]{6}[0-9]{2}S?[0-9]{7,9}$)
- [1-9][0-9]*\.?[0-9]*([Ee][+-]?[0-9]+)?
- (^[+-]?[0-9]+.?[0-9]{0,8}$)|(^not collected$)|(^not provided$)|(^restricted access$)|(^missing: control sample$)|(^missing: sample group$)|(^missing: synthetic construct$)|(^missing: lab stock$)|(^missing: third party data$)|(^missing: data agreement established pre-2023$)|(^missing: endangered species$)|(^missing: human-identifiable$)
- ^(\d|[1-9]\d|\d\.\d{1,2}|[1-9]\d\.\d{1,2}|100)$
- [0-9]*(\.[0-9]*)?
- [+-]?[0-9]+.?[0-9]*
- ((0|((0\.)|([1-9][0-9]*\.?))[0-9]*)([Ee][+-]?[0-9]+)?)|((^not collected$)|(^not provided$)|(^restricted access$)|(^missing: control sample$)|(^missing: sample group$)|(^missing: synthetic construct$)|(^missing: lab stock$)|(^missing: third party data$)|(^missing: data agreement established pre-2023$)|(^missing: endangered species$)|(^missing: human-identifiable$))
- ^150|1[0-4][0-9]|[1-9][0-9]|[0-9]|not provided$
- [0-9]+
- (^[12][0-9]{3}(-(0[1-9]|1[0-2])(-(0[1-9]|[12][0-9]|3[01])(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?(/[0-9]{4}(-[0-9]{2}(-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?)?$)|(^not collected$)|(^not provided$)|(^restricted access$)|(^missing: control sample$)|(^missing: sample group$)|(^missing: synthetic construct$)|(^missing: lab stock$)|(^missing: third party data$)|(^missing: data agreement established pre-2023$)|(^missing: endangered species$)|(^missing: human-identifiable$)
- (^[ESD]RS\d{6,}(,[ESD]RS\d{6,})*$)|(^SAM[END][AG]?\d+(,SAM[END][AG]?\d+)*$)|(^EGAN\d{11}(,EGAN\d{11})*$)
- ([+-]?(0|((0\.)|([1-9][0-9]*\.?))[0-9]*)([Ee][+-]?[0-9]+)?)|((^not collected$)|(^not provided$)|(^restricted access$)|(^missing: control sample$)|(^missing: sample group$)|(^missing: synthetic construct$)|(^missing: lab stock$)|(^missing: third party data$)|(^missing: data agreement established pre-2023$)|(^missing: endangered species$)|(^missing: human-identifiable$))
- (0|((0\.)|([1-9][0-9]*\.?))[0-9]*)([Ee][+-]?[0-9]+)?

</details>

I will create a spreadsheet with the following columns:
- checklist accession
- field name
- pattern

And we can work from there with the suggested improve patterns
