### ISSUE TITLE
remove validation of xml checklists from ENA

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#59]
_This task is a submission stream task._

DoD:
- [x] ENA does not  send XML documents to validation using XML checklists
- [ ] all related code is remove - e.g. checklist xml model classes
- [ ] all related infrastructure is removed - e.g. oracle db

**Comment by dipayan1985** [comment]
The acceptance criterias for replacing XML checklist validation in ENA with JSON schema validation done in BioSamples are as follows:

1. Behaviour (HIGHEST RISK):

The result of validating a sample document against a XML checklist and its corresponding JSON schema should be the same. If sample SAMEX is valid against a XML checklist it should be valid against the corresponding JSON schema and vice-versa. This is very important and if this fails this move will need to be rolled back until the behaviour is fixed.

2. Error messages (LOW RISK):

- Schema validation service/ BioSamples should send unique validation messages to Webin.

E.g. extra error messages for synonyms etc should be filtered out, if collection_date and geographic_location are   mandatory fields and the sample doesn't have those then there should be 2 error messages, 1. collection_date missing, 2. geographic_location missing, text can be different.

3. Performance (HIGH RISK):
The round-robin time of sending a single sample to BioSamples and receiving an accessioned sample is ~70 milliseconds. It is sure to go up by a little bit but we expect the response times to be ~100 milliseconds.
