### ISSUE TITLE
json-schema-store :  ci/cd

### ISSUE THREAD

**Issue by snathanvj** [ebi-ait/checklist#61]
- [x] ci/cd for json-schema-store - using k8s
   - [x] docker file
   - [x] gitlab-ci file
   - [ ] all k8s files: deployment, service, image pull secret etc.
   - [ ] push to branch triggers a build and deployment to k8s
   - [ ] setup external access to service on k8s. See catalogue ticket: ebi-ait/data-catalogue-frontend#11

environments
  - dev server: http://wp-np2-40:8080/ 
  - prod server: https://www.ebi.ac.uk/biosamples/schema/store/

**Comment by amnonkhen** [comment]
The urls should be under the /biosamples path in the ebi domain. Please reconfigure TM to use
www(dev).ebi.ac.uk/biosamples/schema-store
