### ISSUE TITLE
clean and tidy gitlab projects of schema-store and biovalidator

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#63]
new projects deploying to k8s are in https://gitlab.ebi.ac.uk/fairification
old projects deploying to VMs are in https://gitlab.ebi.ac.uk/biosamples

Mongo configuration of schema store is stored in the `biosamples-internal` gitlab repo and copied to the vms during the biosamples build. This is a dependency that needs to be cleaned up.
- addresses and credentials are stored by environment, e.g. for [dev](https://gitlab.ebi.ac.uk/biosamples/biosamples-internal/-/blob/master/dev/application.properties)

old projects need to be retired.

- [ ] clean up config from internal gitlab repo
- [ ] retire old projects

**Comment by snathanvj** [comment]
Assigning it to @theisuru . Isuru will test the stability of new deployment and update the biovalidator endpoints in biosample projects and remove existing vm deployment.
