### ISSUE TITLE
spin up a dev environment for BioSamples

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#66]
currently ENA dev is using BioSamples dev

- [x] provision vms 
   - [x] ticket in [RUP](https://www.ebi.ac.uk/tsi/rup/): [755531](https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=755531)
   - [x] setup software on vm
   - [x] [link to setup script here ](https://gitlab.ebi.ac.uk/biosamples/biosamples-internal/-/blob/master/dev/sw/dev/setup.sh?ref_type=heads)
   - [x] validate new vms
- [x] provision DBs 
  - [x] request new instances: [RUP ticket 755530](https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=755530)
  - [x] setup db, tables, etc.
  - [x] validate new DBs
- [x] setup config files in [biosamples-internal](https://gitlab.ebi.ac.uk/biosamples/biosamples-internal)
- [x] update biosample [gitlab ci/cd pipeline](https://github.com/EBIBioSamples/biosamples-v4/blob/dev/.gitlab-ci.yml)
- [x] update ena dev environment to use the new BioSamples dev environment
- [x] load data to BioSamples dev 
  - [x] samples collection
  - [x] Index all data in Solr 
- [x] @dgupta to communicate to Coleman
   - agree on the duration to complete and service levels
   - ena dev env is only for dev teams, not for en users
   - ena test and prod are for ena users

**Comment by theisuru** [comment]
@dipayan1985 FYI

**Comment by theisuru** [comment]
Sent request for VM and MongoDB via RUP. I could not see any ticket number in RUP.

**Comment by amnonkhen** [comment]
@theisuru to follow up via email with the RUP team

**Comment by theisuru** [comment]
Meanwhile we thought if we can merge our changes with ENA changes we can carry out with the tests. But eventhough ENA developers are happy to move, we need to give 15 days notification via ENA content team. Therefore, having this new dev environment is the best approach as of now.

**Comment by dipayan1985** [comment]
To avoid ERS sample accession duplications and in turn PRIMARY_KEY errors below accession start numbers have been assigned to the new dev database:

SAMEA accession of the new environment starts from SAMEA132000000 (date applicable August 20, 2024)
ERS accession of the new environment starts from ERS31000000 (date applicable August 20, 2024)

**Comment by dipayan1985** [comment]
The new BSD dev environment is a bit unstable, it went down over the weekend with a Mongo DB issue, and also now. This is blocking the deployment of the Webin-REST service in dev which will connect to this environment.

http://wp-np2-44:8082/biosamples/v2/actuator/health -> down

**Comment by theisuru** [comment]
Yeah, it seems. I removed all daily pipelines from cron. Probably NCBI pipeline is too much for this VM with everything running. Will keep an eye on the services.
