### ISSUE TITLE
ERC000026 is missing from schema-store

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#68]
is a EGA checklist. 
This is not available in ENA checklist API, hence not available in schema-store.

**Comment by theisuru** [comment]
Asked Vishnu how we can get all checklists including EGA checklists.

**Comment by theisuru** [comment]
I am getting ENA checklists using the endpoint https://www.ebi.ac.uk/ena/browser/api/summary/ERC000001-ERC999999?offset=0&limit=100
But ERC000026 is not there. Dipayan said this is a EGA checklist, is there any way I can get all the checklist from the API? (edited) 


> Vishnukumar Balavenkataraman Kadhirvelu
>   11:31 AM
> Hi Isuru
> 11:32
> We currently do not support EGA checklist through the browser api
> 
> 
> Isuru Liyanage
>   11:33 AM
> ohh so there is no way to get them using the API?
> Any other way to get them
> 
> Vishnukumar Balavenkataraman Kadhirvelu
>   11:35 AM
> Not through any of our presentation api, but would be better to check with Raj's team

**Comment by theisuru** [comment]
Rajkumar Devaraj
  12:49 PM
Checklist can be accessed from webin-reports, for example: https://www.ebi.ac.uk/ena/submit/report/checklists/ERC000026?type=sample&format=json
See checklist-controller here -> https://www.ebi.ac.uk/ena/submit/report/swagger-ui/index.html (edited) 



:+1:
1



Isuru Liyanage
  12:52 PM
can we use this to get a list of checklists
I tried https://www.ebi.ac.uk/ena/submit/report/checklists?type=sample&format=json

**Comment by amnonkhen** [comment]
The endpoint is the `/checklists/xml/<id>` https://www.ebi.ac.uk/ena/submit/report/checklists/xml/ERC000026?type=sample

**Comment by theisuru** [comment]
1. Change checklist list retrieval url to https://www.ebi.ac.uk/ena/submit/report/checklists?type=sample&format=json
2. Change indivudual checklist retrieval url to https://www.ebi.ac.uk/ena/submit/report/checklists/xml/${checklistId}?type=sample

Now 2 additional checklists are available with this
ERC000026, ERC000046
