### ISSUE TITLE
retirements of synonyms

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#75]
- existing ENA checklists will continue support synonyms
- Each checklist that changes will cease to support synonyms
- Each field will keep just the "main" name
- A checklist user that wants to use the modified checklist would need to upgrade their document to use the :main" values rather than the synonyms.

This is a suggested behaviour.
-  [x] clear this with the ENA content team
Notes [here](https://docs.google.com/document/d/1plHVpQcO0BpP1VyPmePiHL_bDOoNtepX9-jqQmiji-I/edit).

**Comment by Jeena-Rajan** [comment]
Have discussed with Colman (ENA Product Owner) who has confirmed that synonyms will not appear in new versions of checklists but will be available in older versions. Waiting for Peter's confirmation (have sent email)

**Comment by Jeena-Rajan** [comment]
Confirmation received from Peter (email dated 08/08/24)
