### ISSUE TITLE
release revised checklist schemas

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#77]
Definition of Done
- [x] synonym error messages (see #67 )
- [x] include ajv-errors in biovalidator and deploy a new version

**Comment by theisuru** [comment]
Improve synonym error messages by adding `errorMessage` to schema template inside `allof`. This should be used by `ajv-errors`.  
```
"errorMessage": "Just one of the following properties must be specified: 'collection_date', 'collection date', 'Event Date/Time'"
```

**Comment by theisuru** [comment]
Schema store is deployed and revised checklists schemas are available in `wp-np2-44`

**Comment by theisuru** [comment]
Another fix was done to rectify the issue reported by Enrique few weeks back, which also relates to synonyms. 
We now populate a property for each synonym to make sure it has the same structure as the original property.
