### ISSUE TITLE
prod env

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#83]
plan for production rollout:

- [x] k8s cluster - we use the same one. (configure test (wwwdev) and prod (www) )
  - [x] biovalidator
  - [x] schema-store
  - [x] checklist-editor
- [x] namespace - biosamples-prod
- [x] traffic manager rules
- [ ] [deployment procedure](https://docs.google.com/document/d/1CteWn9iRzQZpABfg1m1GL0BTVKIDnMPW4LWncZ0Q_yY/edit?tab=t.0)
  - [x] order of installations (e.g. cehcklist, then biosamples)
  - [x] manual creations of BioSamples checklists - see #165
  - [ ] sanity check (create different ticket and link)
  - [x] rollback procedure 
- [ ] monitoring - nice to have, butnot critical (moved to later)
- [ ] reviews:
   - [ ] Isuru - BioSamples side
   - [ ] Dipayan - ENA Side

**Comment by theisuru** [comment]
As we discussed few weeks ago, the URIs of our services will be as below. @amnonkhen @snathanvj @Jeena-Rajan Let me know if you have any comments

`dev` (biosamples-dev)
- https://wwwint.ebi.ac.uk/biosamples/biovalidator
- https://wwwint.ebi.ac.uk/biosamples/schema-store
- https://wwwint.ebi.ac.uk/biosamples/checklist-editor

`test` (biosamples-test)
- https://wwwdev.ebi.ac.uk/biosamples/biovalidator
- https://wwwdev.ebi.ac.uk/biosamples/schema-store
- https://wwwdev.ebi.ac.uk/biosamples/checklist-editor

`prod` (biosamples-prod)
- https://www.ebi.ac.uk/biosamples/biovalidator
- https://www.ebi.ac.uk/biosamples/schema-store
- https://www.ebi.ac.uk/biosamples/checklist-editor

We will move other biosamples services except `Solr` to k8s same namespaces once we are finished with this deployment.

**Comment by theisuru** [comment]
@snathanvj I started configuring for `wwwdev` and `www` envs. Please use above branches if you are also planning to make any changes.

**Comment by theisuru** [comment]
Cleaning up traffic_manager repository for `wwwint` and `wwwdev`. Next will do the same for `www` and make merge requests. 
- Removing old unsued mappings
- Move scattered config for `biosamples` and `ait` to one place and format
- Add new mappings

**Comment by theisuru** [comment]
The pull request is merged and checklist-editor is working again in `wwwint`. Now need to finish the deployment of `wwwdev` (test) environment. 
We will deploy, but will not connect them with BioSamples as per the comment from Colman today regarding postponing the test deployment until they finish training session start of December.

**Comment by theisuru** [comment]
[Merge request for production routing](https://gitlab.ebi.ac.uk/wp/wp-traffic-manager/-/merge_requests/1462)

Notes:
Production services are only on HX K8s cluster. Do we want them to be also on HH cluster to enable disaster recovery? We need to get access for this cluster to do this.

**Comment by theisuru** [comment]
This ticket contains many small tasks. So we will mark this as complete and handle rest in different tickets. Tobe linked to this ticket as we complete the sub tasks. 
- API monitoring and testing (sanity check)
