### ISSUE TITLE
Improve error messages and prepare users for change

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/checklist#98]
Based on the work done for #81 , we have detected that the error messages could be improved for the user. The main steps are:

1. [x] @ESapenaVentura to talk with Colman to verify if users (Brokers) are parsing the error messages automatically and how we could better warn them about the changes #107 
2. [x] #135
   1. [ ] Current message is: `<sample alias> failed validation due to <dataPath> <error message>`. Suggested message: `<sample alias>, attribute '<dataPath>' failed validation: <error message>`
   2. [ ] Remove duplicated general error
   3. [ ] Remove runtime error
3. [x] #134

**Comment by tburdett** [comment]
Re:
`Suggested message: <sample alias>, attribute '<dataPath>' failed validation: <error message>`

As we discussed, some consumers may be trying to parse or grep these error messages to capture reports. Adding some structure that can be easily tokenised might help, so e.g.

`Validation error for sample: [<sample alias>]; attribute: [<dataPath>]. REASON: [<error message>]`

Easy then to pull apart the content in the square brackets!

**Comment by ESapenaVentura** [comment]
I have spoken with Dipayan regarding the tokenisation of the error message, and he agreed. Waiting
